version: '3.8'

services:

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: shopvn_db
    environment:
      POSTGRES_DB:       ecommerce_db
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout:  5s
      retries:  5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: shopvn_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
